version: "3.8"

networks:
  monitoring:

services:
  fem_demoapp:
    build:
      context: .
    image: fem_demoapp
    restart: unless-stopped
    container_name: fem_demoapp
    ports:
      - 38080:8080
    networks:
      - monitoring
    volumes:
      - $PWD/target/certs:/tmp/certs:ro
