apiVersion: 1

datasources:
  - name: TestData DB
    type: testdata
  - name: Prometheus
    type: prometheus
    access: server
    url: http://fem-prometheus:9090
    editable: true
    uid: "PBFA97CFB590B2093"
  - name: Jaeger
    type: jaeger
    url: http://fem-jaeger-query:16686
    editable: true
    uid: "PC9A941E8F2E49454"
  - name: Loki
    type: loki
    access: direct
    url: http://fem-loki:3100
    editable: true
    uid: "P8E80F9AEF21F6940"
