################################################################################
# see https://grafana.com/docs/loki/latest/configure for configuration details #
################################################################################

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 5m

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index
    cache_location: /tmp/loki/tsdb-cache
  filesystem:
    directory: /tmp/loki/chunks

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 43800h
  split_queries_by_interval: 24h

frontend:
  max_outstanding_per_tenant: 4096 # default = 100]
  compress_responses: true # default = false]
  log_queries_longer_than: 20s

query_range:
  parallelise_shardable_queries: false
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

querier:
  max_concurrent: 2048

analytics:
  reporting_enabled: false
