global:
  scrape_interval:     1m
  scrape_timeout:      30s
  evaluation_interval: 30s

scrape_configs:
  - job_name:       'otlp'
    static_configs:
      - targets: ['fem-otel-collector:5317']
  - job_name: 'es'
    static_configs:
      - targets: ['fem-opensearch-exporter:9114']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['fem-mongodb-exporter:9216']
  - job_name: 'postgresql'
    static_configs:
      - targets: ['fem-postgresql-exporter:9187']
  - job_name: 'shellexporter'
    static_configs:
      - targets: ['fem-shellexporter:9360']
