networks:
  monitoring:

services:
  fem_mongodb_exporter:
    image: percona/mongodb_exporter:2.37.0
    restart: unless-stopped
    container_name: fem_mongodb_exporter
    hostname: fem-mongodb-exporter
    ports:
      - "29216:9216"
    command: [
        "--mongodb.uri=mongodb://{mongodb_username}:{mongodb_password}@{mongodb_hosts}/admin?ssl=true&sslInsecure=true",
        "--mongodb.direct-connect=false",
        "--collector.diagnosticdata=true",
        "--collector.replicasetstatus=true",
        "--collector.indexstats=true",
        "--collector.collstats=true",
        "--log.level=error",
    ]
    networks:
      - monitoring
