version: "3.8"

networks:
  monitoring:

services:
  fem_shellexporter:
    build:
      context: .
    image: fem_shellexporter
    restart: unless-stopped
    container_name: fem_shellexporter
    hostname: fem_shellexporter
    volumes:
      - $PWD/target/shellexporter/metrics:/usr/local/shellexporter/metrics:ro
    ports:
      - 9360:9360
    networks:
      - monitoring
