apiVersion: 1

datasources:
  - name: TestData DB
    type: testdata
  - name: Prometheus
    type: prometheus
    access: server
    url: http://fem_prometheus:9090
    editable: true
  - name: Jaeger
    type: jaeger
    access: direct
    url: http://fem_jaeger:16686
    editable: true
  - name: Loki
    type: loki
    access: direct
    url: http://fem_loki:3100
    editable: true
