name: my-first-action
on: push
jobs:
  test-the-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: check out F.E.M. repository
        uses: actions/checkout@v4
      - name: start F.E.M.
        run: make --file Makefile.fem start
        shell: bash
      - name: start demoapp
        run: make --file Makefile.fem-demoapp start
        shell: bash
      - name: start shellexporter
        run: make --file Makefile.fem-shellexporter start
        shell: bash
      - name: run tests
        id: tests
        run: make --file Makefile.fem-tests run
      - name: set failure
        if: job.steps.tests.status == failure()
        run: exit 1
