name: my-first-action
on: push
jobs:
  test-the-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: check out F.E.M. repository
        uses: actions/checkout@v4
      - name: start F.E.M.
        run: make --file Makefile.fem start && sleep 30s
      - name: start demoapp
        run: make --file Makefile.fem-demoapp start && sleep 60s
        shell: bash
      - name: run tests
        run: make --file Makefile.fem-tests run
